---
- name: Configurar servidor de banco de dados
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yaml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "devopsmaonamassa"
  tasks:
    - name: Configurar hosts lab ansible
      lineinfile: 
        dest: /etc/hosts
        state: present
        line: "{{item}}"
      with_items:
      - 192.168.10.2 control-node
      - 192.168.10.3 app01
      - 192.168.10.4 db01
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
  
   

 
    