
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.name = "master-node"
  config.vm.network "private_network", ip: "192.168.0.1"
  # config.vm.network "forwarded_port", guest: 80, host: 8080
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provision "shell", path: "provision.sh"
  
end
